import { describe, expect, it } from "vitest";
import { sanitizeEmailRichText, sanitizeRichHtml } from "../../src/lib/html-sanitize";

// Bu, önceden yalnızca içe aktarma modülüne özel olan `sanitizeImportedHtml`'in yerini alan
// paylaşılan sanitizer'ı test eder — artık blog/sayfa yazma yolları da AYNI fonksiyonu kullanır
// (bkz. modules/blog/blog.routes.ts, modules/pages/pages.routes.ts).
describe("sanitizeRichHtml", () => {
  it("strips <script> tags and their content entirely", () => {
    const result = sanitizeRichHtml('<p>Hello</p><script>alert("xss")</script>');
    expect(result).toContain("<p>Hello</p>");
    expect(result).not.toContain("script");
    expect(result).not.toContain("alert");
  });

  it("strips <iframe>/<object>/<embed>/<form>", () => {
    const result = sanitizeRichHtml('<iframe src="evil.com"></iframe><object data="x"></object><embed src="x"/><form></form>');
    expect(result).not.toContain("iframe");
    expect(result).not.toContain("object");
    expect(result).not.toContain("embed");
    expect(result).not.toContain("form");
  });

  it("strips on* event handler attributes", () => {
    const result = sanitizeRichHtml('<p onclick="alert(1)">Hello</p>');
    expect(result).not.toContain("onclick");
    expect(result).toContain("Hello");
  });

  it("rejects javascript: URLs in href", () => {
    const result = sanitizeRichHtml('<a href="javascript:alert(1)">click</a>');
    expect(result).not.toContain("javascript:");
  });

  it("rejects data: URLs in img src", () => {
    const result = sanitizeRichHtml('<img src="data:image/png;base64,AAAA">');
    expect(result).not.toContain("data:image");
  });

  it("keeps safe formatting tags and allows <img> with http(s) src", () => {
    const result = sanitizeRichHtml('<p>Hello <strong>world</strong></p><img src="https://example.com/a.png" alt="x">');
    expect(result).toContain("<strong>world</strong>");
    expect(result).toContain('src="https://example.com/a.png"');
  });

  it("returns an empty string for null/undefined/empty input", () => {
    expect(sanitizeRichHtml(null)).toBe("");
    expect(sanitizeRichHtml(undefined)).toBe("");
    expect(sanitizeRichHtml("")).toBe("");
  });

  it("leaves WordPress shortcodes as inert plain text", () => {
    const result = sanitizeRichHtml("[gallery ids=\"1,2,3\"]<p>caption</p>");
    expect(result).toContain("[gallery");
    expect(result).toContain("<p>caption</p>");
  });

  // TipTap `@tiptap/extension-table` (resizable: false) desteği — bkz. html-sanitize.ts başındaki
  // "Tablo desteği" notu.
  describe("table support", () => {
    it("keeps table structure tags and preserves valid colspan/rowspan", () => {
      const result = sanitizeRichHtml(
        '<table><tbody><tr><td colspan="2" rowspan="3">merged</td></tr></tbody></table>',
      );
      expect(result).toContain("<table>");
      expect(result).toContain('colspan="2"');
      expect(result).toContain('rowspan="3"');
      expect(result).toContain("merged");
    });

    it("preserves colspan/rowspan on <th> as well as <td>", () => {
      const result = sanitizeRichHtml('<table><tr><th colspan="2">head</th></tr></table>');
      expect(result).toContain('colspan="2"');
    });

    it("never emits colwidth (not generated by resizable:false TipTap table, not allow-listed)", () => {
      const result = sanitizeRichHtml('<table><tr><td colwidth="100,200">x</td></tr></table>');
      expect(result).not.toContain("colwidth");
    });

    it("clamps an excessively large colspan/rowspan to the max bound instead of dropping the cell", () => {
      const result = sanitizeRichHtml(
        '<table><tr><td colspan="999999999" rowspan="99999">x</td></tr></table>',
      );
      expect(result).toContain('colspan="50"');
      expect(result).toContain('rowspan="50"');
      expect(result).toContain("x");
    });

    it("clamps a non-positive or non-numeric span value to 1", () => {
      const result = sanitizeRichHtml(
        '<table><tr><td colspan="-5" rowspan="abc">x</td></tr></table>',
      );
      expect(result).toContain('colspan="1"');
      expect(result).toContain('rowspan="1"');
    });
  });
});

// §10.16.4 E-posta blok editörü — `text` bloğunun zengin metni. `sanitizeRichHtml`'den AYRI,
// DAHA DAR bir allow-list (bkz. html-sanitize.ts başındaki gerekçe).
describe("sanitizeEmailRichText", () => {
  it("strips <script>/<style>/on* handlers just like sanitizeRichHtml", () => {
    const result = sanitizeEmailRichText('<p onclick="alert(1)">Hi</p><script>alert(1)</script><style>body{}</style>');
    expect(result).toContain("Hi");
    expect(result).not.toContain("onclick");
    expect(result).not.toContain("script");
    expect(result).not.toContain("style");
  });

  it("never allows 'style'/'class'/'id' attributes — layout is the renderer's job, not the user's (§10.16.4)", () => {
    const result = sanitizeEmailRichText('<p style="background:url(javascript:alert(1))" class="x" id="y">Hi</p>');
    expect(result).not.toContain("style=");
    expect(result).not.toContain("class=");
    expect(result).not.toContain('id="y"');
  });

  it("rejects javascript:/data: URLs in <a href> (only http/https/mailto/tel allowed)", () => {
    const result = sanitizeEmailRichText('<a href="javascript:alert(1)">click</a>');
    expect(result).not.toContain("javascript:");
  });

  it("drops tags outside the narrow allow-list (e.g. <h1>, <img>, <table>)", () => {
    const result = sanitizeEmailRichText('<h1>Heading</h1><img src="https://example.com/a.png"><table><tr><td>x</td></tr></table>');
    expect(result).not.toContain("<h1>");
    expect(result).not.toContain("<img");
    expect(result).not.toContain("<table>");
  });

  // Güvenlik düzetmesi (security-agent denetimi) — reverse tabnabbing savunması.
  describe("target=_blank / rel=noopener enforcement (reverse tabnabbing defense-in-depth)", () => {
    it("forces rel='noopener noreferrer' on a target=_blank link even if the caller omitted rel", () => {
      const result = sanitizeEmailRichText('<a href="https://example.com" target="_blank">click</a>');
      expect(result).toContain('rel="noopener noreferrer"');
    });

    it("overrides an attacker-supplied rel value on a target=_blank link (never trusts caller-provided rel)", () => {
      const result = sanitizeEmailRichText('<a href="https://example.com" target="_blank" rel="opener">click</a>');
      expect(result).toContain('rel="noopener noreferrer"');
      expect(result).not.toContain('rel="opener"');
    });

    it("does not add rel on a link without target=_blank", () => {
      const result = sanitizeEmailRichText('<a href="https://example.com">click</a>');
      expect(result).not.toContain("rel=");
    });
  });
});
