/**
 * `.claude/design-notes-doctor-portfolio-console.md` §2.3 — Yabancı Uyruklu kimlik formundaki
 * "Uyruk Ülkesi" seçicisi. Projede aranabilir/combobox bir ülke seçici YOK (design notes'un
 * kararı: native `<select>`, YENİ bir combobox kütüphanesi İCAT EDİLMEZ) — bu liste yalnızca o
 * `<select>`'i beslemek için ISO 3166-1 alpha-2 kod + Türkçe ad çiftleri taşır. `TR` bilinçli
 * olarak listede YOKTUR ([DPI] §2.4 — pasaportu VEREN ülke `"TR"` OLAMAZ).
 */
export interface IsoCountry {
  code: string;
  nameTr: string;
}

export const ISO_COUNTRIES_EXCLUDING_TR: IsoCountry[] = [
  { code: "DE", nameTr: "Almanya" },
  { code: "US", nameTr: "Amerika Birleşik Devletleri" },
  { code: "AD", nameTr: "Andorra" },
  { code: "AO", nameTr: "Angola" },
  { code: "AR", nameTr: "Arjantin" },
  { code: "AM", nameTr: "Ermenistan" },
  { code: "AU", nameTr: "Avustralya" },
  { code: "AT", nameTr: "Avusturya" },
  { code: "AZ", nameTr: "Azerbaycan" },
  { code: "BE", nameTr: "Belçika" },
  { code: "BY", nameTr: "Belarus" },
  { code: "BA", nameTr: "Bosna Hersek" },
  { code: "BR", nameTr: "Brezilya" },
  { code: "BG", nameTr: "Bulgaristan" },
  { code: "TD", nameTr: "Çad" },
  { code: "CZ", nameTr: "Çekya" },
  { code: "CN", nameTr: "Çin" },
  { code: "DK", nameTr: "Danimarka" },
  { code: "EG", nameTr: "Mısır" },
  { code: "EE", nameTr: "Estonya" },
  { code: "FI", nameTr: "Finlandiya" },
  { code: "FR", nameTr: "Fransa" },
  { code: "GE", nameTr: "Gürcistan" },
  { code: "GH", nameTr: "Gana" },
  { code: "GR", nameTr: "Yunanistan" },
  { code: "NL", nameTr: "Hollanda" },
  { code: "IN", nameTr: "Hindistan" },
  { code: "ID", nameTr: "Endonezya" },
  { code: "IQ", nameTr: "Irak" },
  { code: "IR", nameTr: "İran" },
  { code: "IE", nameTr: "İrlanda" },
  { code: "ES", nameTr: "İspanya" },
  { code: "IL", nameTr: "İsrail" },
  { code: "SE", nameTr: "İsveç" },
  { code: "CH", nameTr: "İsviçre" },
  { code: "IT", nameTr: "İtalya" },
  { code: "JP", nameTr: "Japonya" },
  { code: "CA", nameTr: "Kanada" },
  { code: "QA", nameTr: "Katar" },
  { code: "KZ", nameTr: "Kazakistan" },
  { code: "KE", nameTr: "Kenya" },
  { code: "KG", nameTr: "Kırgızistan" },
  { code: "CO", nameTr: "Kolombiya" },
  { code: "KW", nameTr: "Kuveyt" },
  { code: "KR", nameTr: "Güney Kore" },
  { code: "HR", nameTr: "Hırvatistan" },
  { code: "LB", nameTr: "Lübnan" },
  { code: "LY", nameTr: "Libya" },
  { code: "LT", nameTr: "Litvanya" },
  { code: "LU", nameTr: "Lüksemburg" },
  { code: "LV", nameTr: "Letonya" },
  { code: "HU", nameTr: "Macaristan" },
  { code: "MK", nameTr: "Kuzey Makedonya" },
  { code: "MY", nameTr: "Malezya" },
  { code: "MT", nameTr: "Malta" },
  { code: "MA", nameTr: "Fas" },
  { code: "MD", nameTr: "Moldova" },
  { code: "MC", nameTr: "Monako" },
  { code: "ME", nameTr: "Karadağ" },
  { code: "MX", nameTr: "Meksika" },
  { code: "MN", nameTr: "Moğolistan" },
  { code: "NO", nameTr: "Norveç" },
  { code: "NZ", nameTr: "Yeni Zelanda" },
  { code: "OM", nameTr: "Umman" },
  { code: "PK", nameTr: "Pakistan" },
  { code: "PS", nameTr: "Filistin" },
  { code: "PA", nameTr: "Panama" },
  { code: "PE", nameTr: "Peru" },
  { code: "PH", nameTr: "Filipinler" },
  { code: "PL", nameTr: "Polonya" },
  { code: "PT", nameTr: "Portekiz" },
  { code: "RO", nameTr: "Romanya" },
  { code: "RU", nameTr: "Rusya" },
  { code: "SA", nameTr: "Suudi Arabistan" },
  { code: "RS", nameTr: "Sırbistan" },
  { code: "SG", nameTr: "Singapur" },
  { code: "SK", nameTr: "Slovakya" },
  { code: "SI", nameTr: "Slovenya" },
  { code: "SO", nameTr: "Somali" },
  { code: "SD", nameTr: "Sudan" },
  { code: "SY", nameTr: "Suriye" },
  { code: "TJ", nameTr: "Tacikistan" },
  { code: "TH", nameTr: "Tayland" },
  { code: "TN", nameTr: "Tunus" },
  { code: "TM", nameTr: "Türkmenistan" },
  { code: "UA", nameTr: "Ukrayna" },
  { code: "AE", nameTr: "Birleşik Arap Emirlikleri" },
  { code: "GB", nameTr: "Birleşik Krallık" },
  { code: "UY", nameTr: "Uruguay" },
  { code: "UZ", nameTr: "Özbekistan" },
  { code: "VE", nameTr: "Venezuela" },
  { code: "VN", nameTr: "Vietnam" },
  { code: "YE", nameTr: "Yemen" },
  { code: "ZA", nameTr: "Güney Afrika" },
].sort((a, b) => a.nameTr.localeCompare(b.nameTr, "tr"));
